name: Lint ROS2 package
on:
  # Run this action whenever a pull request is made
  pull_request:
  push:
    branches:
      - ros2

jobs:
  # Note that we pass each job a different name to distinguish each linter job
  
  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        linter: [copyright, flake8, pep257, xmllint]
    steps:
      - uses: actions/checkout@main
      - uses: ros-tooling/setup-ros@0.1.2
        with:
          required-ros-distributions: foxy
      - uses: ros-tooling/action-ros-lint@0.1.1
        with:
          distribution: foxy
          linter: ${{ matrix.linter }}
          package-name: |
            create2_description
  
  # TODO: Disabled because of an error:
  # 
  # ament_lint_cmake: error: unrecognized arguments: --linelength
  # 
  # continous_integration:
  #   name: Continuous Integration tests
  #   runs-on: ubuntu-20.04
  #   strategy:
  #     fail-fast: false
  #   steps:
  #     - uses: actions/checkout@main
  #     - uses: ros-tooling/setup-ros@0.1.2
  #       with:
  #         required-ros-distributions: foxy
  #     - uses: ros-tooling/action-ros-ci@master
  #       with:
  #         package-name: create2_description
  #         target-ros2-distro: foxy
